FORMAT: 1A
HOST: http://api.footballcrunch.tv

# We Crunch
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

## Match [/apps/cactus/matches/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `3`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Match [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "name": "Pick-up posters from post-office" }


